services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Change this to a secure password
      MYSQL_DATABASE: mydb               # Your database name
      MYSQL_USER: user                   # Your MySQL user
      MYSQL_PASSWORD: userpassword       # Change this to a secure password
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
